site_name: Weka Wiki
site_url: https://github.com/Waikato/weka-wiki
site_description: Documention on Weka that can also be found in the manual and the example archive that comes with each Weka download (zip or installer).
theme:
    name: readthedocs
    custom_dir: weka_theme/
# if page names start with a blank, eg ' Some name', then they get 
# excluded from the navigation on the left-hand side
pages:
  - 'Home': index.md
  - 'Resources':
    - 'FAQ': faq.md
    - 'Not so FAQ': not_so_faq.md
    - 'Troubleshooting': troubleshooting.md
    - 'Learning resources': learning_resources.md
    - 'Using the API': using_the_api.md
    - 'Extending Weka': extending_weka.md
    - 'ARFF Format': arff.md
  - 'Packages': packages/index.md
  - 'Mailing list': mailing_list.md
  # unlisted pages
  - ' WEKA experiment DatabaseUtils.props' : weka_experiment_database_utils.props.md
  # general
  - ' Subversion': subversion.md
  - ' Get latest Bugfixes': get_latest_bugfixes.md
  - ' Compiling Weka': compiling_weka.md
  - ' Ant': ant.md
  - ' Maven': maven.md
  - ' Snapsnots': snapshots.md
  - ' ARFF (stable version)': arff_stable.md
  - ' ARFF (developer version)': arff_developer.md
  - ' ARFF Syntax Highlighting': arff_syntax.md
  - ' CLASSPATH': classpath.md
  # packages
  - ' Package manager': packages/manager.md
  - ' Unofficial packages': packages/unofficial.md
  - ' How are packages structured for the package management system?': packages/structure.md
  # not so faq
  - ' Generalized Sequential Patterns': not_so_faq/gsp.md
  - ' What do those numbers mean in a J48 tree?': not_so_faq/j48_numbers.md
  # faq
  - ' What are the principal release branches of Weka?': faqs/different_versions.md
  - ' Where can I get old versions of WEKA?': faqs/old_versions.md
  - ' How do I get the latest bugfixes?': faqs/latest_bugfixes.md
  - ' How can I contribute to WEKA?': faqs/contribution.md
  - ' Weka package manager does not start' : faqs/package_manager_doesnt_start.md
  - ' ARFF file does not load' : faqs/arff_does_not_load.md
  - ' Can I use WEKA in commercial applications?' : faqs/commercial_applications.md
  - ' Ubuntu 18:08 BLAS Warning' : faqs/ubuntu_1804_blas_warning.md
  - ' Can I check my CLASSPATH from within WEKA?' : faqs/check_classpath_within_weka.md
  - ' Where is my home directory located?' : faqs/home_directory_location.md
  - ' Can I check how much memory is available for WEKA?' : faqs/check_memory_available.md
  - ' OutOfMemoryException' : faqs/OutOfMemoryException.md
  - ' Can I use CSV files?' : faqs/use_csv_files.md
  - ' CSV File Conversion' : faqs/csv_file_conversion.md
  - ' How do I divide a dataset into training and test sets' : faqs/how_do_i_divide_a_dataset_into_training_and_test_set.md
  - ' How do I generate compatible train and test sets that get processed with a filter? ' : faqs/how_do_i_generate_compatible_train_and_test_sets_that_get_processed_with_a_filter.md
  - ' How do I perform attribute selection? ' : faqs/how_do_i_perform_attribute_selection.md
  - ' How do I perform clustering?' : faqs/how_do_i_perform_clustering.md
  - ' How do I perform text classification?' : faqs/how_do_i_perform_text_classification.md
  - ' How can I perform multi-instance learning in WEKA?' : faqs/how_can_i_perform_multi_instance_learning_in_weka.md
  - ' How do I perform cost-sensitive classification?' : faqs/how_do_i_perform_cost_sensitive_classification.md
  - ' How do I make predictions with a trained model?' : faqs/how_do_i_make_predictions_with_a_trained_model.md
  - ' Why am I missing certain nominal or string values from sparse instances?' : faqs/why_am_i_missing_certain_nominal_or_string_values_from_sparse_instances.md
  - ' Can I use WEKA for time series analysis?' : faqs/can_i_use_weka_for_time_series_analysis.md
  - ' Does WEKA support multi-label classification?' : faqs/does_weka_support_multi_label_classification.md
  - ' How do I perform one-class classification?' : faqs/how_do_i_perform_one_class_classification.md
  - ' Can I make a screenshot of a plot or graph directly in WEKA?' : faqs/can_i_make_a_screenshot_of_a_plot_or_graph_directly_in_weka.md
  - ' How do I use the package manager?' : packages/manager.md
  - ' What do I do if the package manager does not start?' : faqs/package_manager_doesnt_start.md
  - ' Where do I find visualization of classifiers, etc.?' : faqs/visualization.md
  - ' How can I track instances in WEKA?' : faqs/how_can_i_track_instances_in_weka.md
  - ' How do I use ID attributes?' : faqs/how_do_i_use_id_attributes.md
  - ' How do I connect to a database?' : faqs/how_do_i_connect_to_a_database.md
  - ' How do I use WEKA from the command line?' : faqs/how_do_i_use_weka_from_the_command_line.md
  - ' Can I tune the parameters of a classifier?' : faqs/can_i_tune_the_parameters_of_a_classifier.md
  - ' How do I generate Learning curves?' : faqs/how_do_i_generate_learning_curves.md
  - ' Where can I find information regarding ROC curves?' : faqs/where_can_i_find_information_regarding_roc_curves.md
  - ' I have unbalanced data - now what?' : faqs/i_have_unbalanced_data_now_what.md
  - ' Can I run an experiment using clusterers in the Experimenter?' : faqs/can_i_run_an_experiment_using_clusterers_in_the_experimenter.md
  - ' How can I use transactional data in Weka?' : faqs/how_can_i_use_transactional_data_in_weka.md
  - ' How can I use Weka with Matlab or Octave?' : faqs/how_can_i_use_weka_with_matlab_or_octave.md
  - ' Can I change the colors (background, axes, etc.) of the plots in WEKA?' : faqs/can_i_change_the_colors_background_axes_etc_of_the_plots_in_weka.md
  - ' How do I add a new classifier, filter, kernel, etc?' : faqs/how_do_i_add_a_new_classifier_filter_kernel_etc.md
  - ' How do I use libsvm in WEKA?' : faqs/how_do_i_use_libsvm_in_weka.md
  - ' The snowball stemmers dont work, what am I doing wrong?' : faqs/the_snowball_stemmers_dont_work_what_am_i_doing_wrong.md
  - ' Where can I get WEKAs source code?' : faqs/where_can_i_get_wekas_source_code.md
  - ' How do I compile WEKA?' : faqs/how_do_i_compile_weka.md
  - ' What is Subversion and what do I need to do to access it?' : faqs/what_is_subversion_and_what_do_i_need_to_do_to_access_it.md
  - ' How do I use WEKAs classes in my own code?' : faqs/how_do_i_use_wekas_classes_in_my_own_code.md
  - ' How do I write a new classifier or filter?' : faqs/how_do_i_write_a_new_classifier_or_filter.md
  - ' Can I compile WEKA into native code?' : faqs/can_i_compile_weka_into_native_code.md
  - ' Can I use WEKA from C#?' : faqs/can_i_use_weka_from_c_sharp.md
  - ' Can I use WEKA from Python?' : faqs/can_i_use_weka_from_python.md
  - ' Can I use WEKA from Groovy?' : faqs/can_i_use_weka_from_groovy.md
  - ' Serialization is nice, but what about generating actual Java code from WEKA classes?' : faqs/serialization_is_nice_but_what_about_generating_actual_java_code_from_weka_classes.md
  - ' How are packages structured for the package management system?' : packages/index.md
  - ' Pluggable evaluation metrics for classification/regression' : faqs/pluggable_evaluation_metrics.md
  - ' How can I contribute to WEKA?' : faqs/contribution.md
  - ' How do I modify the RunWeka.bat file?' : faqs/how_do_i_modify_the_runwekabat_file.md
  - ' Can I process UTF-8 datasets or files?' : faqs/can_i_process_utf8_datasets_or_files.md
  - ' How do I run the Windows Weka installer in silent mode?' : faqs/how_do_i_run_the_windows_weka_installer_in_silent_mode.md
  - ' I have Weka download problems - what is going wrong?' : faqs/weka_download_problems.md
  - ' My ARFF file does not load - why?' : faqs/arff_does_not_load.md
  - ' What does nominal value not declared in header, read Token[X], line Y mean?' : faqs/arff_does_not_load.md
  - ' How do I get rid of this OutOfMemoryException?' : faqs/OutOfMemoryException.md
  - ' How do I deal with a StackOverflowError?' : faqs/stack_overflow_error.md
  - ' Why do I get the error message "training and test set are not compatible"?' : faqs/why_do_i_get_the_error_message_training_and_test_set_are_not_compatible.md
  - ' Could not read from database: unknown data type' : faqs/couldnt_read_from_database_unknown_data_type.md
  - ' Trying to add JDBC driver: ... - Error, not in CLASSPATH?' : faqs/trying_to_add_jdbc_driver_error_not_in_classpath.md
  - ' I cannot process large datasets - any ideas?' : faqs/i_cannot_process_large_datasets_any_ideas.md

  # just using weka
  - ' Command redirection': command_redirection.md
  - ' Area under the curve': auc.md
  - ' Batch filtering': batch_filtering.md
  - ' ROC Curves': roc_curves.md
  - ' Plotting multiple ROC curves': plotting_multiple_roc_curves.md
  - ' Databases': databases.md
  - ' Converting CSV to ARFF' : converting_csv_to_arff.md
  # using the API
  - ' Use Weka in your Java code': use_weka_in_your_java_code.md
  - ' Weka Examples': weka_examples.md
  - ' Generating cross-validation folds': generating_cv_folds.md
  - ' Generating cross-validation folds (Filter approach)': generating_cv_folds_filter.md
  - ' Generating cross-validation folds (Java approach)': generating_cv_folds_java.md
  - ' Generating cross-validation folds': generating_cv_folds.md
  - ' Creating an ARFF file': creating_arff_file.md
  - ' Creating Instances on-the-fly': creating_instances.md
  - ' Binarize Attribute': binarize_attribute.md
  - ' ARFF files from Text Collections': arff_from_text_collections.md
  - ' Adding attributes to a dataset': adding_attributes_to_dataset.md
  - ' Save Instances to an ARFF File': save_instances_to_arff.md
  - ' Generating ROC curve': generating_roc_curve.md
  - ' Visualizing ROC curve': visualizing_roc_curve.md
  - ' Serialization': serialization.md
  - ' Jupyter Notebooks': jupyter_notebooks.md
  # extending Weka
  - ' Writing your own Classifier': writing_classifier.md
  - ' Writing your own Filter': writing_filter.md

