site_name: Weka Wiki
site_url: https://github.com/Waikato/weka-wiki
site_description: Documention on Weka that can also be found in the manual and the example archive that comes with each Weka download (zip or installer).
theme:
    name: readthedocs
#    custom_dir: weka_theme/
markdown_extensions:
    - toc:
        baselevel: 3
        permalink: "#"
plugins:
    - search
# if page names start with a blank, eg ' Some name', then they get
# excluded from the navigation on the left-hand side
nav:
  - 'Home': index.md
  - 'Downloading and installing Weka': downloading_weka.md
  - 'Requirements': requirements.md
  - 'Documentation': documentation.md
  - 'Getting help': getting_help.md
  - 'Citing Weka': citing_weka.md
  - 'Literature': literature.md
  - 'Development': development.md
  - 'History': history.md
  - 'Resources':
    - 'FAQ': faq.md
    - 'Not so FAQ': not_so_faq.md
    - 'Troubleshooting': troubleshooting.md
    - 'Using the API': using_the_api.md
    - 'Extending Weka': extending_weka.md
    - 'ARFF Format': formats_and_processing/arff.md
    - 'Primer' : primer.md
    - 'Datasets' : datasets.md
    - 'Visualization Articles' : visualization_articles.md
    - 'Properties File' : properties_file.md
    - 'Packages': packages/index.md
    - 'Experimenter' : experimenter/experimenter.md
