site_name: Weka Wiki
site_url: https://github.com/Waikato/weka-wiki
site_description: Documention on Weka that can also be found in the manual and the example archive that comes with each Weka download (zip or installer).
theme:
    name: readthedocs
    custom_dir: weka_theme/
# if page names start with a blank, eg ' Some name', then they get 
# excluded from the navigation on the left-hand side
nav:
  - 'Home': index.md
  - 'Downloading and installing Weka': downloading_weka.md
  - 'Requirements': requirements.md
  - 'Documentation': documentation.md
  - 'Getting help': getting_help.md
  - 'Citing Weka': citing_weka.md
  - 'Literature': literature.md
  - 'Development': development.md
  - 'History': history.md
  - 'Resources':
    - 'FAQ': faq.md
    - 'Not so FAQ': not_so_faq.md
    - 'Troubleshooting': troubleshooting.md
    - 'Learning resources': learning_resources.md
    - 'Using the API': using_the_api.md
    - 'Extending Weka': extending_weka.md
    - 'ARFF Format': formats_and_processing/arff.md
    - 'Primer' : primer.md
    - 'Datasets' : datasets.md
    - 'Visualization Articles' : visualization_articles.md
    - 'Properties File' : properties_file.md
  - 'Packages': packages/index.md
  - 'Experimenter' : experimenter/experimenter.md
  - 'Mailing list': mailing_list.md
  - 'Academic or Related Projects' : academic/academic_or_related_projects.md
  # general
  - ' Subversion': subversion.md
  - ' Get latest Bugfixes': get_latest_bugfixes.md
  - ' Compiling Weka': compiling_weka.md
  - ' Snapsnots': snapshots.md
  - ' CLASSPATH': classpath.md
  # packages
  - ' Package manager': packages/manager.md
  - ' Unofficial packages': packages/unofficial.md
  - ' How are packages structured for the package management system?': packages/structure.md
  - ' How are packages structured for the package management system?' : packages/index.md  
  # not so faq
  - ' Generalized Sequential Patterns': not_so_faq/gsp.md
  - ' How do I use the associator GeneralizedSequentialPatterns?' : how_do_i_use_the_associator_generalized_sequential_patterns.md
  - ' What do those numbers mean in a J48 tree?': not_so_faq/j48_numbers.md
  # faq - general
  - ' What are the principal release branches of Weka?': faqs/different_versions.md
  - ' Where can I get old versions of WEKA?': faqs/old_versions.md
  - ' How do I get the latest bugfixes?': faqs/latest_bugfixes.md
  - ' Can I check my CLASSPATH from within WEKA?' : faqs/check_classpath_within_weka.md
  - ' Where is my home directory located?' : faqs/home_directory_location.md
  - ' Can I check how much memory is available for WEKA?' : faqs/check_memory_available.md
  - ' Can I use WEKA in commercial applications?' : faqs/commercial_applications.md
  # faq - basic usage
  - ' Can I use CSV files?' : faqs/use_csv_files.md
  - ' CSV File Conversion' : faqs/csv_file_conversion.md
  - ' How do I divide a dataset into training and test sets' : faqs/how_do_i_divide_a_dataset_into_training_and_test_set.md
  - ' How do I generate compatible train and test sets that get processed with a filter? ' : faqs/how_do_i_generate_compatible_train_and_test_sets_that_get_processed_with_a_filter.md
  - ' How do I perform attribute selection? ' : faqs/how_do_i_perform_attribute_selection.md
  - ' How do I perform clustering?' : faqs/how_do_i_perform_clustering.md
  - ' Where do I find visualization of classifiers, etc.?' : faqs/visualization.md
  - ' How do I perform text classification?' : faqs/how_do_i_perform_text_classification.md
  - ' How can I perform multi-instance learning in WEKA?' : faqs/how_can_i_perform_multi_instance_learning_in_weka.md
  - ' How do I perform cost-sensitive classification?' : faqs/how_do_i_perform_cost_sensitive_classification.md
  - ' How do I make predictions with a trained model?' : faqs/how_do_i_make_predictions_with_a_trained_model.md
  - ' Why am I missing certain nominal or string values from sparse instances?' : faqs/why_am_i_missing_certain_nominal_or_string_values_from_sparse_instances.md
  - ' Can I use WEKA for time series analysis?' : faqs/can_i_use_weka_for_time_series_analysis.md
  - ' Does WEKA support multi-label classification?' : faqs/does_weka_support_multi_label_classification.md
  - ' How do I perform one-class classification?' : faqs/how_do_i_perform_one_class_classification.md
  - ' Can I make a screenshot of a plot or graph directly in WEKA?' : faqs/can_i_make_a_screenshot_of_a_plot_or_graph_directly_in_weka.md
  - ' How do I use the package manager?' : packages/manager.md
  - ' What do I do if the package manager does not start?' : faqs/package_manager_doesnt_start.md
  - ' Weka package manager does not start' : faqs/package_manager_doesnt_start.md
  # faq - Advanced usage
  - ' How can I track instances in WEKA?' : faqs/how_can_i_track_instances_in_weka.md
  - ' How do I use ID attributes?' : faqs/how_do_i_use_id_attributes.md
  - ' How do I connect to a database?' : faqs/how_do_i_connect_to_a_database.md
  - ' How do I use WEKA from the command line?' : faqs/how_do_i_use_weka_from_the_command_line.md
  - ' Can I tune the parameters of a classifier?' : faqs/can_i_tune_the_parameters_of_a_classifier.md
  - ' How do I generate Learning curves?' : faqs/how_do_i_generate_learning_curves.md
  - ' Where can I find information regarding ROC curves?' : faqs/where_can_i_find_information_regarding_roc_curves.md
  - ' I have unbalanced data - now what?' : faqs/i_have_unbalanced_data_now_what.md
  - ' Can I run an experiment using clusterers in the Experimenter?' : faqs/can_i_run_an_experiment_using_clusterers_in_the_experimenter.md
  - ' How can I use transactional data in Weka?' : faqs/how_can_i_use_transactional_data_in_weka.md
  - ' How can I use Weka with Matlab or Octave?' : faqs/how_can_i_use_weka_with_matlab_or_octave.md
  # faq - Customizing Weka
  - ' Can I change the colors (background, axes, etc.) of the plots in WEKA?' : faqs/can_i_change_the_colors_background_axes_etc_of_the_plots_in_weka.md
  - ' How do I add a new classifier, filter, kernel, etc?' : faqs/how_do_i_add_a_new_classifier_filter_kernel_etc.md
  # faq - Using third party tools
  - ' How do I use libsvm in WEKA?' : faqs/how_do_i_use_libsvm_in_weka.md
  - ' The snowball stemmers dont work, what am I doing wrong?' : faqs/the_snowball_stemmers_dont_work_what_am_i_doing_wrong.md
  # faq - Developing with Weka
  - ' Where can I get WEKAs source code?' : faqs/where_can_i_get_wekas_source_code.md
  - ' How do I compile WEKA?' : faqs/how_do_i_compile_weka.md
  - ' What is Subversion and what do I need to do to access it?' : faqs/what_is_subversion_and_what_do_i_need_to_do_to_access_it.md
  - ' How do I use WEKAs classes in my own code?' : faqs/how_do_i_use_wekas_classes_in_my_own_code.md
  - ' How do I write a new classifier or filter?' : faqs/how_do_i_write_a_new_classifier_or_filter.md
  - ' Can I compile WEKA into native code?' : faqs/can_i_compile_weka_into_native_code.md
  - ' Can I use WEKA from C#?' : faqs/can_i_use_weka_from_c_sharp.md
  - ' Can I use WEKA from Python?' : faqs/can_i_use_weka_from_python.md
  - ' Can I use WEKA from Groovy?' : faqs/can_i_use_weka_from_groovy.md
  - ' Serialization is nice, but what about generating actual Java code from WEKA classes?' : faqs/serialization_is_nice_but_what_about_generating_actual_java_code_from_weka_classes.md
  - ' How are packages structured for the package management system?': packages/structure.md # duplicate entry
  - ' How are packages structured for the package management system?' : packages/index.md # duplicate entry
  - ' Pluggable evaluation metrics for classification/regression' : faqs/pluggable_evaluation_metrics.md
  - ' How can I contribute to WEKA?' : faqs/contribution.md
  # faq - Windows
  - ' How do I modify the CLASSPATH?' : how_do_i_modify_the_classpath.md
  - ' How do I modify the RunWeka.bat file?' : faqs/how_do_i_modify_the_runwekabat_file.md
  - ' Can I process UTF-8 datasets or files?' : faqs/can_i_process_utf8_datasets_or_files.md
  - ' How do I run the Windows Weka installer in silent mode?' : faqs/how_do_i_run_the_windows_weka_installer_in_silent_mode.md
  # faq - Troubleshooting
  - ' I have Weka download problems - what is going wrong?' : faqs/weka_download_problems.md
  - ' My ARFF file does not load - why?' : faqs/arff_does_not_load.md
  - ' ARFF file does not load' : faqs/arff_does_not_load.md
  - ' What does nominal value not declared in header, read Token[X], line Y mean?' : faqs/arff_does_not_load.md
  - ' How do I get rid of this OutOfMemoryException?' : faqs/OutOfMemoryException.md
  - ' How do I deal with a StackOverflowError?' : faqs/stack_overflow_error.md
  - ' Why do I get the error message "training and test set are not compatible"?' : faqs/why_do_i_get_the_error_message_training_and_test_set_are_not_compatible.md
  - ' Could not read from database: unknown data type' : faqs/couldnt_read_from_database_unknown_data_type.md
  - ' Trying to add JDBC driver: ... - Error, not in CLASSPATH?' : faqs/trying_to_add_jdbc_driver_error_not_in_classpath.md
  - ' I cannot process large datasets - any ideas?' : faqs/i_cannot_process_large_datasets_any_ideas.md
  - ' Ubuntu 18:08 BLAS Warning' : faqs/ubuntu_1804_blas_warning.md
  - ' OutOfMemoryException' : faqs/OutOfMemoryException.md
  - ' KnowledgeFlow toolbars are empty' : knowledge_flow_toolbars_are_empty.md
  - ' OSX Mountain Lion - Weka x-y-z is damaged and cannot be installed. You should eject the disk image' : osx_mountain_lion_weka_x_y_z_is_damaged_and_cant_be_installed_you_should_eject_the_disk_image.md
  - ' GUIChooser starts but not Experimenter or Explorer' : gui_chooser_starts_but_not_experimenter_or_explorer.md
  - ' CLASSPATH problems' : classpath_problems.md
  # just using weka
  - ' Command redirection': command_redirection.md
  - ' Area under the curve': auc.md
  - ' Batch filtering': batch_filtering.md
  - ' ROC Curves': roc_curves.md
  - ' Plotting multiple ROC curves': plotting_multiple_roc_curves.md
  - ' Databases': databases.md
  - ' Converting CSV to ARFF' : formats_and_processing/converting_csv_to_arff.md # duplicate entry
  - ' Making predictions' : making_predictions.md
  - ' Use Weka with the Microsoft .NET Framework' : use_weka_with_the_microsoft_net_framework.md
  - ' Using a new Java framework to create ARFF from JPA Entity' : using_a_new_java_framework_to_create_arff_from_jpa_entity.md
  - ' Using cluster algorithms' : using_cluster_algorithms.md
  - ' Using clusterers' : using_clusterers.md
  - ' Using the Experiment API' : experimenter/using_the_experiment_api.md # duplicate entry
  - ' Using the MathExpression filter' : using_the_mathexpression_filter.md
  - ' Using Weka from Groovy' : using_weka_from_groovy.md
  - ' Using Weka from Jython' : using_weka_from_jython.md
  - ' Using Weka via Jepp' : using_weka_via_jepp.md
  # using the API
  - ' Use Weka in your Java code': use_weka_in_your_java_code.md
  - ' Weka Examples': weka_examples.md
  - ' Generating cross-validation folds': generating_cv_folds.md
  - ' Generating cross-validation folds (Filter approach)': generating_cv_folds_filter.md
  - ' Generating cross-validation folds (Java approach)': generating_cv_folds_java.md
  - ' Creating Instances on-the-fly': creating_instances.md
  - ' Binarize Attribute': binarize_attribute.md
  - ' Adding attributes to a dataset': adding_attributes_to_dataset.md
  - ' Generating ROC curve': generating_roc_curve.md
  - ' Serialization': serialization.md
  - ' GenericObjectEditor' : generic_object_editor.md
  - ' GenericObjectEditor (book version)' : generic_object_editor_book_version.md
  - ' GenericObjectEditor (developer version)' : generic_object_editor_developer_version.md
  - ' ZeroR' : zero_r.md
  - ' Stemmers' : stemmers.md
  - ' Stop word filtering and attributes' : stop_word_filtering_and_attributes.md
  - ' Text categorization with Weka' : text_categorization_with_weka.md
  - ' Text classification with Weka' : text_classification_with_weka.md
  - ' Tuning classifier parameters' : tuning_classifier_parameters.md
  - ' Performing attribute selection' : performing_attribute_selection.md
  - ' Mathematical functions' : mathematical_functions.md
  - ' MessageClassifier' : message_classifier.md
  - ' MetaCost' : metacost.md
  - ' LibSVM' : lib_svm.md
  - ' Saving and loading models' : saving_and_loading_models.md
  - ' Removing misclassified instances from dataset' : removing_misclassified_instances_from_dataset.md
  - ' J48-Weighter patch' : j48_weighter_patch.md
  - ' FilteredClassifierUpdateable' : filtered_classifier_updateable.md
  - ' Multi-instance classification' : multi_instance_classification.md
  - ' Optimizing parameters' : optimizing_parameters.md
  - ' Generating source code from Weka classes' : generating_source_code_from_weka_classes.md  
  - ' Generating and saving a precision-recall curve' : generating_and_saving_a_precision_recall_curve.md
  - ' Generating classifier evaluation output manually' : generating_classifier_evaluation_output_manually.md
  - ' Instance ID' : instance_id.md
  - ' Discretizing Datasets' : discretizing_datasets.md
  - ' CostMatrix' : cost_matrix.md
  - ' CostSensitiveClassifier' : cost_sensitive_classifier.md  
  - ' Classifying large datasets' : classifying_large_datasets.md  
  - ' Add weights to dataset' : add_weights_to_dataset.md 
  # Technical Reference
  - ' Ant': ant.md
  - ' Maven': maven.md
  - ' Jupyter Notebooks': jupyter_notebooks.md  
  - ' GPGPU' : gpgpu.md
  - ' Java Virtual Machine' : java_virtual_machine.md
  - ' JVM' : jvm.md
  - ' just-in-time (JIT) compiler' : just_in_time_jit_compiler.md
  - ' Memory consumption and Garbage collector' : memory_consumption_and_garbage_collector.md  
  # Experimenter
  #- 'Experimenter' : experimenter/experimenter.md
  - ' Learning curves' : experimenter/learning_curves.md
  - ' Remote Experiment' : experimenter/remote_experiment.md
  - ' Running an Experiment Using Clusterers' : experimenter/running_an_experiment_using_clusterers.md
  - ' Using the Experiment API' : experimenter/using_the_experiment_api.md
  # Academic or Related Projects
  #- 'Academic or Related Projects' : academic/academic_or_related_projects.md
  - ' Related Projects' : academic/related_projects.md
  - ' Related Research Groups' : academic/related_research_groups.md
  - ' Paper References' : academic/paper_references.md
  - ' PROMPT' : academic/prompt.md
  - ' Piqle' : academic/piqle.md
  # Guides
    # extending Weka
  - ' Writing your own Classifier': writing_classifier.md
  - ' Writing your own Filter': writing_filter.md
  - ' Writing your own Classifier Article' : writing_classifier_article.md  
    # General
  - ' Windows Databases' : windows_databases.md
  - ' MS SQL Server 2000 (Desktop Engine)' : ms_sql_server_2000_desktop_engine.md
  - ' Transferring an ARFF file into a database' : formats_and_processing/transferring_an_arff_file_into_a_database.md # duplicate entry
  - ' Weka For Newbies' : weka_for_newbies.md
  - ' Weka on a memory stick' : weka_on_a_memory_stick.md
  - ' Remote Experiment' : experimenter/remote_experiment.md # duplicate entry
  - ' Running an Experiment Using Clusterers' : experimenter/running_an_experiment_using_clusterers.md # duplicate entry
  - ' IKVM with Weka tutorial' : ikvm_with_weka_tutorial.md
  - ' Feature extraction from images' : feature_extraction_from_images.md  
  - ' Ensemble Selection' : ensemble_selection.md
  - ' Document Classification' : document_classification.md  
  - ' Classifying large datasets' : classifying_large_datasets.md # duplicate entry
  - ' Adding tabs in the Explorer' : adding_tabs_in_the_explorer.md  
  - ' How to run Weka schemes from commandline' : how_to_run_weka_schemes_from_commandline.md
  # Formats and Processing
  - ' ARFF (stable version)': formats_and_processing/arff_stable.md
  - ' ARFF (developer version)': formats_and_processing/arff_developer.md
  - ' ARFF files from Text Collections': formats_and_processing/arff_from_text_collections.md
  - ' ARFF Syntax Highlighting': formats_and_processing/arff_syntax.md
  - ' Creating an ARFF file': formats_and_processing/creating_arff_file.md
  - ' Converting CSV to ARFF' : formats_and_processing/converting_csv_to_arff.md
  - ' Save Instances to an ARFF File': formats_and_processing/save_instances_to_arff.md
  - ' XRFF' : formats_and_processing/xrff.md
  - ' XML' : formats_and_processing/xml.md
  - ' Remove Attributes' : formats_and_processing/remove_attributes.md
  - ' Rename Attribute Values' : formats_and_processing/rename_attribute_values.md
  - ' Load an XML BIF file' : formats_and_processing/load_an_xml_bif_file.md
  - ' Transferring an ARFF file into a database' : formats_and_processing/transferring_an_arff_file_into_a_database.md
  - ' Single quotes in labels of ARFF files' : formats_and_processing/single_quotes_in_labels_of_arff_files.md
  - ' Spaces in labels of ARFF files' : formats_and_processing/spaces_in_labels_of_arff_files.md  
  # Props Files
  #- 'Properties File' : properties_file.md
  - ' Props file' : props_file.md
  - ' Where does WEKA look for .props files?' : where_does_weka_look_for_props_files.md  
  - ' WEKA experiment DatabaseUtils.props' : weka_experiment_database_utils.props.md  
  - ' weka/core/Capabilities.props' : weka_core_capabilities.props.md
  - ' weka/core/logging/Logging.props' : weka_core_logging_logging.props.md
  - ' weka/gui/GenericObjectEditor.props' : weka_gui_generic_object_editor.props.md
  - ' weka/gui/GUIEditors.props' : weka_gui_gui_editors.props.md
  - ' weka/gui/GenericPropertiesCreator.props' : weka_gui_generic_properties_creator.props.md
  - ' weka/gui/GenericPropertiesCreator.excludes' : weka_gui_generic_properties_creator.excludes.md
  - ' weka/gui/LookAndFeel.props' : weka_gui_look_and_feel.props.md
  - ' weka/gui/MemoryUsage.props' : weka_gui_memory_usage.props.md
  - ' weka/gui/SimpleCLI.props' : weka_gui_simple_cli.props.md
  - ' weka/gui/beans/Beans.props' : weka_gui_beans_beans.props.md
  - ' weka/gui/experiment/Experimenter.props' : weka_gui_experiment_experimenter.props.md
  - ' weka/gui/explorer/Explorer.props' : weka_gui_explorer_explorer.props.md
  - ' weka/gui/scripting/Groovy.props' : weka_gui_scripting_groovy.props.md
  - ' weka/gui/scripting/Jython.props' : weka_gui_scripting_jython.props.md
  - ' weka/gui/treevisualizer/TreeVisualizer.props' : weka_gui_tree_visualizer_tree_visualizes.props.md
  - ' weka/gui/visualize/Visualize.props' : weka_gui_visualize_visualize.props.md
  # Visualization
  #- 'Visualization Articles' : visualization_articles.md
  - ' Visualizing a Tree' : visualization/visualizing_a_tree.md
  - ' Visualizing cluster assignments' : visualization/visualizing_cluster_assignments.md
  - ' Visualizing ROC curve': visualization/visualizing_roc_curve.md
  - ' Changing the plot background' : visualization/changing_the_plot_background.md 
  - ' Displaying results of cross-validation folds' : visualization/displaying_results_of_cross_validation_folds.md
  - ' Explorer error visualization plugins' : visualization/explorer_error_visualization_plugins.md
  - ' Explorer graph visualization plugins' : visualization/explorer_graph_visualization_plugins.md
  - ' Explorer prediction visualization plugins' : visualization/explorer_prediction_visualization_plugins.md
  - ' Explorer tree visualization plugins' : visualization/explorer_tree_visualization_plugins.md
  - ' Explorer visualization plugins' : visualization/explorer_visualization_plugins.md
  - ' Exporting Charts from the Knowledge Flow' : visualization/exporting_charts_from_the_knowledge_flow.md
  - ' Extensions for WEKAs main GUI' : visualization/extensions_for_wekas_main_gui.md      
  - ' Plotting error rate for incremental classifier' : visualization/plotting_error_rate_for_incremental_classifier.md  
