site_name: Weka Wiki
site_url: https://github.com/Waikato/weka-wiki
site_description: Documention on Weka that can also be found in the manual and the example archive that comes with each Weka download (zip or installer).
theme:
    name: readthedocs
    custom_dir: weka_theme/
# if page names start with a blank, eg ' Some name', then they get 
# excluded from the navigation on the left-hand side
pages:
  - 'Home': index.md
  - 'Resources':
    - 'FAQ': faq.md
    - 'Not so FAQ': not_so_faq.md
    - 'Troubleshooting': troubleshooting.md
    - 'Learning resources': learning_resources.md
    - 'Using the API': using_the_api.md
    - 'Extending Weka': extending_weka.md
    - 'ARFF Format': arff.md
  - 'Packages': packages/index.md
  - 'Mailing list': mailing_list.md
  # unlisted pages
  # general
  - ' Subversion': subversion.md
  - ' Get latest Bugfixes': get_latest_bugfixes.md
  - ' Compiling Weka': compiling_weka.md
  - ' Ant': ant.md
  - ' Maven': maven.md
  - ' Snapsnots': snapshots.md
  - ' ARFF (stable version)': arff_stable.md
  - ' ARFF (developer version)': arff_developer.md
  - ' ARFF Syntax Highlighting': arff_syntax.md
  - ' CLASSPATH': classpath.md
  # packages
  - ' Package manager': packages/manager.md
  - ' Unofficial packages': packages/unofficial.md
  - ' How are packages structured for the package management system?': packages/structure.md
  # not so faq
  - ' Generalized Sequential Patterns': not_so_faq/gsp.md
  - ' What do those numbers mean in a J48 tree?': not_so_faq/j48_numbers.md
  # faq
  - ' What are the principal release branches of Weka?': faqs/different_versions.md
  - ' Where can I get old versions of WEKA?': faqs/old_versions.md
  - ' How do I get the latest bugfixes?': faqs/latest_bugfixes.md
  - ' How can I contribute to WEKA?': faqs/contribution.md
  - ' Weka package manager does not start' : faqs/package_manager_doesnt_start.md
  - ' ARFF file does not load' : faqs/arff_does_not_load.md
  - ' Can I use WEKA in commercial applications?' : faqs/commercial_applications.md
  - ' Ubuntu 18:08 BLAS Warning' : faqs/ubuntu_1804_blas_warning.md
  - ' Can I check my CLASSPATH from within WEKA?' : faqs/check_classpath_within_weka.md
  - ' Where is my home directory located?' : faqs/home_directory_location.md
  - ' Can I check how much memory is available for WEKA?' : faqs/check_memory_available.md
  - ' OutOfMemoryException' : faqs/OutOfMemoryException.md
  - ' Can I use CSV files?' : faqs/use_csv_files.md
  - ' CSV File Conversion' : faqs/csv_file_conversion.md
  - ' How do I divide a dataset into training and test sets' : faqs/how_do_i_divide_a_dataset_into_training_and_test_set.md
  - ' How do I generate compatible train and test sets that get processed with a filter? ' : faqs/how_do_i_generate_compatible_train_and_test_sets_that_get_processed_with_a_filter.md
  - ' How do I perform attribute selection? ' : faqs/how_do_i_perform_attribute_selection.md
  - ' How do I perform clustering?' : faqs/how_do_i_perform_clustering.md
  - ' How do I perform text classification?' : faqs/how_do_i_perform_text_classification.md
  - ' How can I perform multi-instance learning in WEKA?' : faqs/how_can_i_perform_multi_instance_learning_in_weka.md
  - ' How do I perform cost-sensitive classification?' : faqs/how_do_i_perform_cost_sensitive_classification.md
  - ' How do I make predictions with a trained model?' : faqs/how_do_i_make_predictions_with_a_trained_model.md
  - ' Why am I missing certain nominal or string values from sparse instances?' : faqs/why_am_i_missing_certain_nominal_or_string_values_from_sparse_instances.md
  - ' Can I use WEKA for time series analysis?' : faqs/can_i_use_weka_for_time_series_analysis.md
  - ' Does WEKA support multi-label classification?' : faqs/does_weka_support_multi_label_classification.md
  - ' How do I perform one-class classification?' : faqs/how_do_i_perform_one_class_classification.md
  - ' Can I make a screenshot of a plot or graph directly in WEKA?' : faqs/can_i_make_a_screenshot_of_a_plot_or_graph_directly_in_weka.md
  - ' How do I use the package manager?' : packages/manager.md
  - ' What do I do if the package manager does not start?' : faqs/package_manager_doesnt_start.md
  - ' Where do I find visualization of classifiers, etc.?' : faqs/visualization.md
  # just using weka
  - ' Command redirection': command_redirection.md
  - ' Area under the curve': auc.md
  - ' Batch filtering': batch_filtering.md
  - ' ROC Curves': roc_curves.md
  - ' Plotting multiple ROC curves': plotting_multiple_roc_curves.md
  - ' Databases': databases.md
  - ' Converting CSV to ARFF' : converting_csv_to_arff.md
  # using the API
  - ' Use Weka in your Java code': use_weka_in_your_java_code.md
  - ' Weka Examples': weka_examples.md
  - ' Generating cross-validation folds': generating_cv_folds.md
  - ' Generating cross-validation folds (Filter approach)': generating_cv_folds_filter.md
  - ' Generating cross-validation folds (Java approach)': generating_cv_folds_java.md
  - ' Generating cross-validation folds': generating_cv_folds.md
  - ' Creating an ARFF file': creating_arff_file.md
  - ' Creating Instances on-the-fly': creating_instances.md
  - ' Binarize Attribute': binarize_attribute.md
  - ' ARFF files from Text Collections': arff_from_text_collections.md
  - ' Adding attributes to a dataset': adding_attributes_to_dataset.md
  - ' Save Instances to an ARFF File': save_instances_to_arff.md
  - ' Generating ROC curve': generating_roc_curve.md
  - ' Visualizing ROC curve': visualizing_roc_curve.md
  - ' Serialization': serialization.md
  - ' Jupyter Notebooks': jupyter_notebooks.md
  # extending Weka
  - ' Writing your own Classifier': writing_classifier.md
  - ' Writing your own Filter': writing_filter.md

