site_name: Weka Wiki
site_url: https://github.com/Waikato/weka-wiki
site_description: Documention on Weka that can also be found in the manual and the example archive that comes with each Weka download (zip or installer).
theme:
    name: readthedocs
    custom_dir: weka_theme/
# if page names start with a blank, eg ' Some name', then they get 
# excluded from the navigation on the left-hand side
pages:
  - 'Home': index.md
  - 'Resources':
    - 'FAQ': faq.md
    - 'Not so FAQ': not_so_faq.md
    - 'Troubleshooting': troubleshooting.md
    - 'Learning resources': learning_resources.md
  - 'Packages': packages/index.md
  - 'Mailing list': mailing_list.md
  # unlisted pages
  # general
  - ' subversion': subversion.md
  - ' get latest bugfixes': get_latest_bugfixes.md
  - ' compiling weka': compiling_weka.md
  - ' ant': ant.md
  # packages
  - ' Package manager': packages/manager.md
  - ' Unofficial packages': packages/unofficial.md
  - ' How are packages structured for the package management system?': packages/structure.md
  # not so faq
  - ' Generalized Sequential Patterns': not_so_faq/gsp.md
  - ' What do those numbers mean in a J48 tree?': not_so_faq/j48_numbers.md
  # faq
  - ' What are the principal release branches of Weka?': faqs/different_versions.md
  - ' Where can I get old versions of WEKA?': faqs/old_versions.md
  - ' How do I get the latest bugfixes?': faqs/latest_bugfixes.md
  - ' How can I contribute to WEKA?': faqs/contribution.md
  - ' Weka package manager does not start' : faqs/package_manager_doesnt_start.md

