site_name: Weka Wiki
site_url: https://github.com/Waikato/weka-wiki
site_description: Documention on Weka that can also be found in the manual and the example archive that comes with each Weka download (zip or installer).
theme:
    name: readthedocs
    custom_dir: weka_theme/
# if page names start with a blank, eg ' Some name', then they get 
# excluded from the navigation on the left-hand side
pages:
  - 'Home': index.md
  - 'Resources':
    - 'FAQ': faq.md
    - 'Not so FAQ': not_so_faq.md
    - 'Troubleshooting': troubleshooting.md
    - 'Learning resources': learning_resources.md
    - 'Using the API': using_the_api.md
    - 'Extending Weka': extending_weka.md
    - 'ARFF Format': arff.md
  - 'Packages': packages/index.md
  - 'Mailing list': mailing_list.md
  # unlisted pages
  # general
  - ' Subversion': subversion.md
  - ' Get latest Bugfixes': get_latest_bugfixes.md
  - ' Compiling Weka': compiling_weka.md
  - ' Ant': ant.md
  - ' Maven': maven.md
  - ' Snapsnots': snapshots.md
  - ' ARFF (stable version)': arff_stable.md
  - ' ARFF (developer version)': arff_developer.md
  - ' ARFF Syntax Highlighting': arff_syntax.md
  # packages
  - ' Package manager': packages/manager.md
  - ' Unofficial packages': packages/unofficial.md
  - ' How are packages structured for the package management system?': packages/structure.md
  # not so faq
  - ' Generalized Sequential Patterns': not_so_faq/gsp.md
  - ' What do those numbers mean in a J48 tree?': not_so_faq/j48_numbers.md
  # faq
  - ' What are the principal release branches of Weka?': faqs/different_versions.md
  - ' Where can I get old versions of WEKA?': faqs/old_versions.md
  - ' How do I get the latest bugfixes?': faqs/latest_bugfixes.md
  - ' How can I contribute to WEKA?': faqs/contribution.md
  - ' Weka package manager does not start' : faqs/package_manager_doesnt_start.md
  - ' ARFF file does not load' : faqs/arff_does_not_load.md
  # just using weka
  # using the API
  - ' Use Weka in your Java code': use_weka_in_your_java_code.md
  - ' Weka Examples': weka_examples.md
  - ' Generating cross-validation folds': generating_cv_folds.md
  - ' Generating cross-validation folds (Filter approach)': generating_cv_folds_filter.md
  - ' Generating cross-validation folds (Java approach)': generating_cv_folds_java.md
  - ' Generating cross-validation folds': generating_cv_folds.md
  - ' Creating an ARFF file': creating_arff_file.md
  - ' Creating Instances on-the-fly': creating_instances.md
  - ' Binarize Attribute': binarize_attribute.md
  - ' ARFF files from Text Collections': arff_from_text_collections.md
  - ' Adding attributes to a dataset': adding_attributes_to_dataset.md
  # extending Weka

